# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Task(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, amplitude: float=None, phase: float=None):  # noqa: E501
        """Task - a model defined in Swagger

        :param amplitude: The amplitude of this Task.  # noqa: E501
        :type amplitude: float
        :param phase: The phase of this Task.  # noqa: E501
        :type phase: float
        """
        self.swagger_types = {
            'amplitude': float,
            'phase': float
        }

        self.attribute_map = {
            'amplitude': 'amplitude',
            'phase': 'phase'
        }

        self._amplitude = amplitude
        self._phase = phase

    @classmethod
    def from_dict(cls, dikt) -> 'Task':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The task of this Task.  # noqa: E501
        :rtype: Task
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amplitude(self) -> float:
        """Gets the amplitude of this Task.


        :return: The amplitude of this Task.
        :rtype: float
        """
        return self._amplitude

    @amplitude.setter
    def amplitude(self, amplitude: float):
        """Sets the amplitude of this Task.


        :param amplitude: The amplitude of this Task.
        :type amplitude: float
        """

        self._amplitude = amplitude

    @property
    def phase(self) -> float:
        """Gets the phase of this Task.


        :return: The phase of this Task.
        :rtype: float
        """
        return self._phase

    @phase.setter
    def phase(self, phase: float):
        """Sets the phase of this Task.


        :param phase: The phase of this Task.
        :type phase: float
        """

        self._phase = phase
